// mediasfu_reactjs/src/components/transforms/VideoCardTransformer.tsx
import React from "react";
import { VideoCard } from "mediasfu-reactjs";

/**
 * Intercepts <VideoCard> children and applies participant-card styling.
 * 
 * Usage:
 *   <VideoCardTransformer>
 *     <VideoCard ... />
 *   </VideoCardTransformer>
 */
export function VideoCardTransformer({ children }: { children: React.ReactNode }) {
  return (
    <>
      {React.Children.map(children, (child) => {
        // Make sure it's a valid React element
        if (!React.isValidElement(child)) return child;

        // Check if the child is actually a VideoCard
        if (child.type === VideoCard) {
          // Extract original props
          const originalProps = child.props;

          // Merge or override the original props
          const newProps = {
            ...originalProps,
            
            // Add or override className so we can use .participant-card CSS
            className: "participant-card",

            // Add or override custom styles for rounded video card
            customStyle: {
              ...(originalProps.customStyle || {}),
              width: "120px",
              height: "120px",
              borderRadius: "50%", // Makes the video rounded
              position: "relative",
              overflow: "hidden",
              boxShadow: "0 2px 8px rgba(0,0,0,0.2)",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
            },

            // Add custom overlays (if not already handled by VideoCard)
            videoControlsComponent: (
              <div className="participant-audio-status">
                {/* Example: Mic Icon */}
                {originalProps.participant?.muted ? (
                  <span className="icon-muted">🔇</span>
                ) : (
                  <span className="icon-active">🎤</span>
                )}
              </div>
            ),
            videoInfoComponent: (
              <div className="participant-name">
                {originalProps.participant?.name || "Unnamed"}
              </div>
            ),
          };

          // Create a cloned element with our newProps
        return React.cloneElement(child, newProps);
        }

        // If it's not a VideoCard, return it untouched
        return child;
      })}
    </>
  );
}

// mediasfu_angular/src/app/components/transforms/video-card-transformer-components/video-card-transformer.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { VideoCardOptions, CustomMediaComponent, VideoCard } from 'mediasfu-angular';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-video-card-transformer',
  template: `
<div class="video-grid">
  <div *ngFor="let row of videoCards; let rowIndex = index" class="video-row">
    <ng-container *ngFor="let video of row">
      <app-video-card
        *ngIf="video.inputs && video.inputs.videoStream"
        [ngClass]="{'hidden': !video.inputs}"
        [customStyle]="transformStyle(video.inputs)"
        [videoStream]="video.inputs.videoStream"
        [participant]="video.inputs.participant"
        [videoControlsComponent]="renderControls(video.inputs)"
        [videoInfoComponent]="renderInfo(video.inputs)"
        [parameters]="video.inputs.parameters"
      ></app-video-card>
    </ng-container>
  </div>
</div>

  `,
  styleUrls: ['./video-card-transformer.component.css'],
  imports: [VideoCard, CommonModule],
})
export class VideoCardTransformerComponent implements OnInit {
  @Input() videoCards: CustomMediaComponent[][] = [];

  constructor() { }

  ngOnInit(): void { }

  transformStyle(video: VideoCardOptions): Partial<CSSStyleDeclaration> {
    return {
      ...video.customStyle,
      width: '120px',
      height: '120px',
      borderRadius: '50%',
      position: 'relative',
      overflow: 'hidden',
      boxShadow: '0 2px 8px rgba(0,0,0,0.2)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    };
  }

  renderControls(video: VideoCardOptions): HTMLElement {
    return `
      <div class="participant-audio-status">
        ${video.participant?.muted! ? '🔇' : '🎤'}
      </div>
    ` as unknown as HTMLElement;
  }

  renderInfo(video: VideoCardOptions): HTMLElement {
    return `
      <div class="participant-name">
        ${video.participant?.name! || 'Unnamed'}
      </div>
    ` as unknown as HTMLElement;
  }
}
