// mediasfu_angular/src/app/components/participant-card-components/participant-card.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  ViewChild,
  ElementRef,
  OnInit,
  AfterViewInit,
  OnChanges,
} from '@angular/core';
import { ParticipantData, Space } from '../../../types';
import { DomSanitizer } from '@angular/platform-browser';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import {
  faCrown,
  faMicrophone,
  faMicrophoneSlash,
  faEnvelope,
  faTrash,
  faCheck,
  faTimes,
} from '@fortawesome/free-solid-svg-icons';

@Component({
  selector: 'app-participant-card',
  templateUrl: './participant-card.component.html',
  styleUrls: ['./participant-card.component.css'],
  imports: [CommonModule, FontAwesomeModule, FormsModule],
})
export class ParticipantCardComponent implements OnInit, AfterViewInit, OnChanges {
  @Input() participant!: ParticipantData;
  @Input() isHost: boolean = false;
  @Input() currentUserId?: string;
  @Input() space!: Space;
  @Input() videoStream?: MediaStream;

  @Output() onMute = new EventEmitter<string>();
  @Output() onToggleMic = new EventEmitter<string>();
  @Output() onSendMessage = new EventEmitter<string>();
  @Output() onRemoveParticipant = new EventEmitter<string>();


  @ViewChild('videoElement', { static: true })
  videoElement!: ElementRef<HTMLVideoElement>;

  // Font Awesome Icons
  faCrown = faCrown;
  faMicrophone = faMicrophone;
  faMicrophoneSlash = faMicrophoneSlash;
  faEnvelope = faEnvelope;
  faTrash = faTrash;
  faCheck = faCheck;
  faTimes = faTimes;

  showActions: boolean = false;
  showRemoveParticipant: boolean = false;

  constructor(private sanitizer: DomSanitizer) {}

  ngOnInit(): void {}

  ngAfterViewInit(): void {
    this.updateVideoStream();
  }

  ngOnChanges(): void {
    this.updateVideoStream();
  }

  private updateVideoStream(): void {
    if (this.videoElement && this.videoStream) {
      const videoElement = this.videoElement.nativeElement;

      // Update the video element's srcObject only if it has changed
      if (videoElement.srcObject !== this.videoStream) {
        videoElement.srcObject = this.videoStream;
      }
    }
  }

  get displayName(): string {
    return this.participant.displayName || 'Unnamed';
  }

  get roleLabel(): string {
    const roleLabels: { [key: string]: string } = {
      host: 'Host',
      speaker: 'Speaker',
      listener: 'Listener',
      requested: 'Requested',
    };
    return roleLabels[this.participant.role] || 'Participant';
  }

  handleDoubleClick(): void {
    if (this.participant.role === 'requested' && this.isHost && !this.space?.rejectedSpeakers.includes(this.participant.id)) {
      this.showActions = !this.showActions;
    } else if (this.isHost && this.participant.role !== 'host') {
      this.showRemoveParticipant = !this.showRemoveParticipant;
    }
  }

  handleMute(): void {
    this.onMute.emit(this.participant.id);
  }

  handleToggleMic(): void {
    this.onToggleMic.emit(this.participant.id);
  }

  handleSendMessage(): void {
    this.onSendMessage.emit(this.participant.id);
  }

  handleRemoveParticipant(): void {
    this.onRemoveParticipant.emit(this.participant.id);
    this.showRemoveParticipant = false;
  }

  approveRequest(): void {
    // Emit event or call service to approve request
    this.showActions = false;
  }

  rejectRequest(): void {
    // Emit event or call service to reject request
    this.showActions = false;
  }
}

<div class="participant-card" (dblclick)="handleDoubleClick()">
  <!-- Host Icon -->
  <fa-icon
    *ngIf="participant.role === 'host'"
    [icon]="faCrown"
    class="fa-crown"
  ></fa-icon>

  <!-- Video Stream -->
  <video
    #videoElement
    autoplay
    muted
    playsinline
    class="participant-avatar"
    [ngStyle]="{ display: videoStream ? 'flex' : 'none' }"
  ></video>

  <!-- Avatar -->
  <img
    *ngIf="!videoStream"
    [src]="participant.avatarUrl || 'https://www.mediasfu.com/logo192.png'"
    alt="{{ displayName }}"
    class="participant-avatar"
  />

  <!-- Participant Details -->
  <div class="participant-name">{{ displayName }}</div>
  <div class="participant-role">{{ roleLabel }}</div>

  <!-- Audio Controls -->
  <div class="participant-controls">
    <div
      class="participant-audio-status"
      (click)="participant.id === currentUserId && handleToggleMic()"
      *ngIf="participant.role !== 'listener' && !isHost"
    >
      <fa-icon
        [icon]="participant.muted ? faMicrophoneSlash : faMicrophone"
      ></fa-icon>
    </div>

    <!-- Mute Button -->
    <button
      *ngIf="
        isHost &&
        participant.id !== currentUserId &&
        participant.role !== 'listener' &&
        !participant.muted
      "
      class="mute-other-btn"
      (click)="handleMute()"
    >
      <fa-icon [icon]="faMicrophoneSlash"></fa-icon>
    </button>
  </div>

  <!-- Request Actions -->
  <div *ngIf="showActions" class="participant-request-actions">
    <button
      class="accept-btn"
      (click)="approveRequest()"
      title="Approve as Speaker"
    >
      <fa-icon [icon]="faCheck"></fa-icon>
    </button>
    <button class="reject-btn" (click)="rejectRequest()" title="Reject Request">
      <fa-icon [icon]="faTimes"></fa-icon>
    </button>
  </div>

  <!-- Remove Button -->
  <button
    *ngIf="showRemoveParticipant"
    class="remove-btn"
    (click)="handleRemoveParticipant()"
  >
    <fa-icon [icon]="faTrash"></fa-icon>
  </button>
</div>

// mediasfu_reactjs/src/components/ParticipantCard.tsx
import { approveRequest, rejectRequest } from "api";
import { useEffect, useRef, useState } from "react";
import {
  FaMicrophoneSlash,
  FaMicrophone,
  FaCrown,
  FaCheck,
  FaTimes,
  FaTrash,
} from "react-icons/fa";
import { ParticipantData, Space } from "types";

const ParticipantCard: React.FC<{
  participant: ParticipantData;
  currentUserId?: string;
  isHost: boolean;
  onMute: (id: string) => void;
  onToggleMic?: (participant: ParticipantData) => void;
  onRemove: (id: string) => void;
  space?: Space;
  video?: MediaStream;
}> = ({
  participant,
  isHost,
  onMute,
  currentUserId,
  onToggleMic,
  onRemove,
  space,
  video,
}) => {
  const [show, setShow] = useState(false);
  const [showRemove, setShowRemove] = useState(false);
  const videoRef = useRef<HTMLVideoElement>(null);

  const micIcon =
    participant.muted && participant.muted === true ? (
      <FaMicrophoneSlash className="icon-muted" />
    ) : (
      <FaMicrophone className="icon-active" />
    );

  const handleParticipantDoubleClick = () => {
    if (
      participant.role === "requested" &&
      isHost &&
      !space?.rejectedSpeakers.includes(participant.id)
    ) {
      setShow(!show);
    } else if (isHost && participant.role !== "host") {
      setShowRemove(!showRemove);
    }
  };

  useEffect(() => {
    if (videoRef.current && video && videoRef.current.srcObject !== video) {
      videoRef.current.srcObject = video;
    }
  }, [video]);

  return (
    <div
      className="participant-card"
      onDoubleClick={handleParticipantDoubleClick}
    >
      {participant.role === "host" && <FaCrown className="fa-crown" />}

      {!video ? (
        <img
          src={participant.avatarUrl || "https://www.mediasfu.com/logo192.png"}
          alt={participant.displayName}
          className="participant-avatar"
        />
      ) : (
        <video
          ref={videoRef}
          autoPlay
          playsInline
          muted
          className="participant-avatar"
        />
      )}

      <div className="participant-name">{participant.displayName}</div>
      <div className={`participant-role ${participant.role}`}>
        {participant.role === "host" && "Host"}
        {participant.role === "speaker" && "Speaker"}
        {participant.role === "listener" && "Listener"}
        {participant.role === "requested" && "Requested"}
      </div>
      {participant.role !== "listener" && participant.id === currentUserId && (
        <div
          className="participant-audio-status"
          onClick={() => onToggleMic && onToggleMic(participant)}
        >
          {micIcon}
        </div>
      )}
      {show && (
        <div className="participant-request-actions">
          <button
            className="accept-btn"
            onClick={() => {
              approveRequest(space?.id!, participant.id, true);
              setShow(false);
            }}
            title="Approve as Speaker"
          >
            <FaCheck />
          </button>
          <button
            className="reject-btn"
            onClick={() => {
              rejectRequest(space?.id!, participant.id);
              setShow(false);
            }}
            title="Reject Request"
          >
            <FaTimes />
          </button>
        </div>
      )}
      {showRemove && (
        <button
          className="remove-btn"
          onClick={() => {
            onRemove(participant.id);
            setShowRemove(false);
          }}
          title="Remove Participant"
        >
          <FaTrash />
        </button>
      )}
      {isHost && participant.role !== "host" && !participant.muted && (
        <button
          className="mute-other-btn"
          onClick={() => onMute(participant.id)}
          title="Mute Participant"
        >
          <FaMicrophoneSlash />
        </button>
      )}
    </div>
  );
};

export default ParticipantCard;
